services:
  - type: web
    name: tn2026-elections-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.13
